title: Monster-big blog
subtitle: Keep coding,Keep heart
link: Homepage link
meta:
  description: 坚持写码，保持一颗平常心，不搞文艺，不做屌丝。
  keywords: !!seq
    - Monster-big
    - 招呼
    - 知识积累、快乐分享
    - MySQL
    - PHP
    - Nginx
    - 数据结构
    - C++
  author: monster-big
master:
  name: monster
  about: 专注且只能做一件事
  email: GugoTianFei@gmail.com
rss:
  title: monster-bi 博客
  desc: 工作经验积累
  lang: zh-cn
  max: 10
copyright:
  owner: monster-big
  beginYear: 2014
  endYear: 2014
theme: default
codetheme: night
